apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nginx-hello-world
  namespace: sekerbank-devops
spec:
  selector:
    app: nginx-hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-hello-world
    spec:
      containers:
        - name: nginx-hello-world
          image: image-registry.openshift-image-registry.svc:5000/sekerbank-devops/nginx-hello-world:latest
          ports:
            - containerPort: 8080
